# Generated by Django 3.2 on 2021-05-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210516_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=120)),
                ('ip', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('query', models.TextField(default='none')),
            ],
        ),
    ]
